export const ACTION = {
    FETCH_LOGIN_SUCCESS: 'FETCH_LOGIN_SUCCESS',
    FETCH_LOGIN_ERROR: 'FETCH_LOGIN_ERROR',
    FETCH_LOGOUT_SUCCESS: 'FETCH_LOGOUT_SUCCESS',
    FETCH_SEARCH_SUCCESS: 'FETCH_SEARCH_SUCCESS',
};
